export const environment = {
  production: true,
  platformProviderApiBaseUrl: 'https://flowboard-fake-api.onrender.com',
  platformProviderEmployeesEndpointPath: '/employees',
  platformProviderAreasEndpointPath: '/areas',
  platformProviderPositionsEndpointPath: '/positions',
  platformProviderJobAssignmentsEndpointPath: '/job-assignments',
  platformProviderEmployeeDocumentsEndpointPath: '/employee-documents',
  platformProviderOfficesEndpointPath: '/offices',
  platformProviderDevicesEndpointPath: '/devices',
  platformProviderReadingsEndpointPath: '/environmental-readings',
  platformProviderMetricThresholdsEndpointPath: '/metric-thresholds',
  platformProviderThresholdRangesEndpointPath: '/threshold-ranges',
  platformProviderBenefitTypesEndpointPath: '/benefit-types',
  platformProviderBenefitAssignmentsEndpointPath: '/benefit-assignments',
  platformProviderVacationBalancesEndpointPath: '/vacation-balances',
  platformProviderPayrollPeriodsEndpointPath: '/payroll-periods',
  platformProviderPayslipsEndpointPath: '/payslips',
  platformProviderAttendanceRecordsEndpointPath: '/attendance-records',
  platformProviderWorkSchedulesEndpointPath: '/work-schedules',
  platformProviderPunchesEndpointPath: '/punches',
  platformProviderRequestsEndpointPath: '/requests',
  platformProviderUserAccountsEndpointPath: '/user-accounts',
  platformProviderRolesEndpointPath: '/roles',
  platformProviderRequestTypesEndpointPath: '/request-types',
  humanResourcesAreaId: 1,
  defaultActingEmployeeId: 1,
};